apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: edu21-helm-db
  namespace: argocd
  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: edu21
  
  source:
    repoURL: https://github.com/shclub/edu14-2.git
    targetRevision: HEAD
    path: charts/helm-db
  
  destination:
    server: https://kubernetes.default.svc
    namespace: edu21
  
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true   
    # Namespace Auto-Creation ensures that namespace specified as the application destination exists in the destination cluster.  
    syncOptions:
      - CreateNamespace=false   
